### ISSUE TITLE
Unexptected token ::

### ISSUE THREAD

**Issue by mswiszcz** [Crecto/crecto#104]
Hey, nice work with the library, though I have one problem 

I am creating a model like this

```
    schema "shows" do
      field :name, String
      field :language, String
      field :rating, Float64
      field :imdb_id, String
      field :votes, Int32
      has_many :episodes, Models::Episode
    end
```

and it crashes on `has_many` relation 

```
Syntax error in expanded macro: has_many:35: unexpected token: ::

              item.as(Episode).models::show_id.as(PkeyValue)
```

any idea why?

**Comment by fridgerator** [comment]
I don't know, but I should have time tonight to take a look at it.

**Comment by fridgerator** [comment]
@mswiszcz can you try using master branch and see if its working for you?  I just pushed an update.

**Comment by mswiszcz** [comment]
@fridgerator works with `has_many` now, but with `belongs_to` I still have the same problem. Maybe similar fix there may help? :)

**Comment by fridgerator** [comment]
yep, looks like I missed that case in belongs_to.  Pushed another commit to master, let me know if that helps.

**Comment by mswiszcz** [comment]
@fridgerator work good :100: Thank you! :)
