### ISSUE TITLE
blocking insert

### ISSUE THREAD

**Issue by jney** [Crecto/crecto#109]
Hello, i'm doing a `Repo.insert` but the execution stop on this instruction

```crystal
begin
  changeset = Repo.insert(user) # stopped here none of the above code is reached
  puts changeset.errors
rescue
  puts "rescued!"
end
puts "after"
```

Obviously i have a DB error:

```
postgres_1  | ERROR:  duplicate key value violates unique constraint "users_email_key"
postgres_1  | DETAIL:  Key (email)=(test@test.com) already exists.
postgres_1  | STATEMENT:  INSERT INTO users (email) VALUES ($1) RETURNING *
```

When i have no DB error the code works just find

**Comment by faultyserver** [comment]
Seems potentially related to #76.

**Comment by fridgerator** [comment]
It looks like the issue was resolved in crystal-pg [#100](https://github.com/will/crystal-pg/pull/100) however there hasn't been a release since then.  @jney if you switch to crystal-pg master branch / commit does this fix the problem for you?

**Comment by jney** [comment]
it still doesn't work for me, is there anything i have to do?

**Comment by fridgerator** [comment]
Interesting, I'll have to do some testing this weekend.

**Comment by fridgerator** [comment]
Potentially this: https://github.com/will/crystal-pg/issues/101

**Comment by fridgerator** [comment]
@jney it seems to be fixed now in crystal-pg 0.13.4 ( released yesterday )

I just created a pull request #123 that adds a `unique_constraint` method which will catch unique constraint database errors and convert them to changeset errors.
